### ISSUE TITLE
Стиль вызова конструктора

### ISSUE THREAD

**Issue by Igor-Kholupko** [AvelJUl/IDoneIt#5]
Встречаются различные варианты написания вызова конструкторов ([ссылка](https://github.com/AvelJUl/IDoneIt/blob/63791ed893dc7d9dfb4fbc7ad39cc0223afd0b05/src/core/models.py#L93)): со сноской аргументов и без сноски (в строчку).

```
description = models.TextField(
    _('description'),
    null=True,
    blank=True
)
tracker = models.CharField(_('tracker'), max_length=14,  choices=TRACKERS)
```

**Comment by AvelJUl** [comment]
Исправлено.
